apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret-bus1
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCZRTNh9RnbX4p76AB/X4veYBKc7QhmJjxDh4/XKjEAw5NxebmhbL9+oSMG4gNkEe6he27kc/Y6cH01uPbzMxmzjdzmSyWXVwsFWjracQhn2UcpROW4rfm8EPJwpuDYE/Yb6ZDTkIcwxI/tbcFtCvXRfE1gH9t8OvxToDyIwY/DRwLekWeN96BBUYMs0aUTQqZS0TBfN9K322SUNhPupsXJCIYwwfhsgM2Owa7Ir/zlY+wFsOSakx4XHjORHrOmBWk5XElkTrfYO0R3MGcGc2metWzKx2StXhXfgKwPpOf01te9wmrIivLSBm+deTOGGDoGavj9g3il/3p/hlyKn4SFHmZhpbKQqbycaAZiZcUhSj4QHYlJHelOxP0dPO/gMlHe8xbzCjTB0x7xiIZ3LG1euWlXprvh5xHBvt4NhHfBpqoN+0LxtzWYE4ATEf7+OVmbWbMxuyjKNF8r1AMEVM/zTnN7hD2cnVlctCglL80x5uaQCOB+wS42aHvIJ2v2QJTjC4b+nTXHQKdpUQ1MW96WB8+fffRgHXjdjIfb5eFPboa7xC/OZqDHwI7GTkJiFE1CBG7JHaL0fKrcIle8PdEDN5vE+M08Nqj25XNC6Dvvkzz5Zbr8sieKT58w48GQZe9GHvVvSBNUZTNyeoHPqGKOKNxK5scRJ1eV3MnB/H/KTKXmHrxYkLMwyhvIK4QbVFWzrSS+mg==
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret-bus1
      namespace: cicd
    type: Opaque
status: {}
