apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAMPoOy1lu+V4v2IvuNRz5hdYJkdrOtOMYI4LzFXBTK5LTKV4+9bf2gljw+DLEocSC6N2H25Esn50Hf+8r0M8uJVvHXYGY76biCkr9hD5OX9/bOVRzA+DGoku4YsV7s7AsumnChzXJJsXoW0WBQaHrKasnuQ8DtZmXJVRTozcLL1ulCb0LgGnl9vqvtfQgWTLYPoaT52oJN01CS0Sc9k30kGHZDL+7R0Rq4nXSF/BjphxcUkUFZea3FurP/zy+9yM9dh3bnCwK42PUa4y6j21NdTIQlqbNNOA6T5bhIxdKlfCmJbc5+na1khLwmoSDeLK/0lU5JVrX9hqrTy5or/HnOqPe244kHcZH8jS9qumYM0dnJ5Ym+C2h8DGTOpz2Em4rYv2tDdd7KvANHk+HIw+DnmmklZpt3KWexsA31P3MLfp2ZStd/iVEw2pQAz6CYDLdsJNu0LWqAPDuybin8LKys+OZhMdngEMk2iL3t87E9csKutrcUp926motju9Jec8x8GxKHgNWjFsHid5tvRzIj07lFIxgso5joNKzcL35HYZCUqd6psDurBtDIKM3SiAd6A8Oy6dBS9zlUNyxSylSPxnJfhJe+AlUbwoCKLK7E0wKg8VVIoUTE1mVe8+c+mDtHNMn7xj8OeLSafOxC7i2AI0sLwIoAzgxMjRa/FTuEztiKpnTKt42Nkt+3X1NmydLzwt+BvXA=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
